state_creators:
    - tidyup_actions/state_creator_robot_pose robot_location location at-base location
    - tidyup_actions/state_creator_robot_location_in_room robot_location location
goal_creators:
    - tidyup_actions/goal_creator_tidyup_objects
action_executors:
    - tidyup_actions/action_executor_pickup_object pickup-object /tidyup/grasping_action
    - tidyup_actions/action_executor_putdown_object putdown-object /tidyup/placing_action
    - tidyup_actions/action_executor_detect_objects detect-objects /tidyup/detect_objects /tidyup/request_graspability table2_loc4
    - tidyup_actions/action_executor_detect_door_state detect-door-state /tidyup/detect_door_state
    - tidyup_actions/action_executor_open_door_service open-door /tidyup/open_door
    - planner_navigation_actions/action_executor_ros_navigation drive-base move_base start recent-detected-objects false
    - tidyup_actions/action_executor_drive_through_door drive-through-door move_base
    - tidyup_actions/action_executor_arm_to_carry arm-to-carry /tidyup/post_grasp_position_action arm-state arm_at_carry
    - tidyup_actions/action_executor_arm_to_side arm-to-side /tidyup/side_position_action arm-state arm_at_side
