state_creators:
    - tidyup_place_actions/state_creator_tidyup_object
goal_creators:
    - tidyup_place_actions/goal_creator_tidyup_object
action_executors:
    - tidyup_place_actions/action_executor_detect_graspable_objects detect-objects /tidyup/request_graspable_objects
    - tidyup_place_actions/action_executor_grasp_object grasp /learned_grasping/learned_grasping_action
    - tidyup_place_actions/action_executor_place_object place /learned_grasping/learned_placing_action
    - tidyup_actions/action_executor_arm_to_carry arm-to-post-grasp /learned_grasping/post_grasp_position_action arm-position arm_post_grasped
    - tidyup_actions/action_executor_arm_to_side arm-to-side /arm_to_side arm-position arm_at_side
    - planner_navigation_actions/action_executor_ros_navigation drive-base move_base
